
new Vue({
    el: "#app",
    data: {
        lessons: [
            {
                id: 1,
                subject: "Math",
                location: "Hendon",
                price: 100,
                spaces: 5,
                image: "FrontEnd/images/math.png",
            },
            {
                id: 2,
                subject: "English",
                location: "Colindale",
                price: 80,
                spaces: 3,
                image: "FrontEnd/images/english.png",
            },
            {
                id: 3,
                subject: "Science",
                location: "Brent Cross",
                price: 120,
                spaces: 2,
                image: "FrontEnd/images/science.png",
            },
            {
                id: 4,
                subject: "History",
                location: "Golders Green",
                price: 90,
                spaces: 1,
                image: "FrontEnd/images/history.png",
            },
            {
                id: 5,
                subject: "Art",
                location: "Hendon",
                price: 75,
                spaces: 0,
                image: "FrontEnd/images/art.png",
            },
            {
                id: 6,
                subject: "Music",
                location: "Kingsbury",
                price: 110,
                spaces: 4,
                image: "FrontEnd/images/music.png",
            },
            {
                id: 7,
                subject: "Physics",
                location: "Harrow",
                price: 150,
                spaces: 2,
                image: "FrontEnd/images/physics.png",
            },
            {
                id: 8,
                subject: "Chemistry",
                location: "Hendon",
                price: 100,
                spaces: 6,
                image: "FrontEnd/images/chemistry.png",
            },
            {
                id: 9,
                subject: "Biology",
                location: "Wembley",
                price: 130,
                spaces: 4,
                image: "FrontEnd/images/biology.png",
            },
            {
                id: 10,
                subject: "Geography",
                location: "Hendon",
                price: 95,
                spaces: 3,
                image: "FrontEnd/images/geography.png",
            },
        ],
        cart: [],
        name: "",
        phone: "",
        searchQuery: "",
        sortBy: "subject",
        sortOrder: "asc",
        showCheckoutPage: false,
        nameError: "",
        phoneError: "",
    },
});
